---
- name: Wait for yum lock release
  shell: ps -aux | grep yum
  register: yum_lock
  retries: 20
  delay: 6
  until: yum_lock.stdout_lines|length <= 2
  changed_when: false

- name: Install docker, pip, development tools
  become: true
  yum:
    name:
      - docker
      - python2-pip
      - "@Development Tools"
    lock_timeout: 600

- name: Install docker compose
  become: true
  pip:
    name: docker-compose

- name: Start docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Add ec2-user to docker group
  user:
    name: "ec2-user"
    groups: "docker"
    append: yes
  become: true

- name: Reset ssh connection to allow ec2-user use docker group
  meta: reset_connection
