#  Deploy CRM api test
#
#  ansible-playbook ansible/deploy.yml
#

---
- name: Build docker image
  hosts: localhost
  roles:
    - build-docker-image
  vars:
    AWS_ACCOUNT_ID: "{{ lookup('env', 'AWS_ACCOUNT_ID') }}"
    AWS_REGION: "{{ lookup('env', 'AWS_REGION') }}"
    ECR_REPOSITORY: crm_api_test
    REPO: "{{ AWS_ACCOUNT_ID }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/{{ ECR_REPOSITORY }}"
    VERSION_TAG: "{{ lookup('env', 'VERSION') }}"
    BUILD_TAG: "build_{{ lookup('env', 'BUILD_NUMBER') }}"
    DOCKERFILE: "docker/Dockerfile"

