#  Deploy CRM api test
#
#  ansible-playbook ansible/deploy.yml
#

---
- name: Build docker image
  hosts: localhost
  roles:
    - build-docker-image
  vars:
    AWS_ACCOUNT_ID: "{{ lookup('env', 'AWS_ACCOUNT_ID') }}"
    AWS_REGION: "{{ lookup('env', 'AWS_REGION') }}"
    ECR_REPOSITORY: crm_api_test
    REPO: "{{ AWS_ACCOUNT_ID }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/{{ ECR_REPOSITORY }}"
    VERSION_TAG: "{{ lookup('env', 'VERSION') }}"
    BUILD_TAG: "build_{{ lookup('env', 'BUILD_NUMBER') }}"
    DOCKERFILE: "docker/Dockerfile"

- name: Add instance to inventory group
  hosts: localhost
  roles:
    - add-instance-to-inventory-group
  vars:
    NAME_TAG: "{{ lookup('env', 'NAME_TAG') }}"
    AWS_REGION: "{{ lookup('env', 'AWS_REGION') }}"
    ANSIBLE_USER: ec2-user

- name: Deploy composed container
  hosts: added_hosts
  roles:
    - deploy-composed-containers
  vars:
    AWS_ACCOUNT_ID: "{{ lookup('env', 'AWS_ACCOUNT_ID') }}"
    AWS_REGION: "{{ lookup('env', 'AWS_REGION') }}"
    ECR_REPOSITORY: crm_api_test
    REPO: "{{ AWS_ACCOUNT_ID }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/{{ ECR_REPOSITORY }}"
    CLIENT_ID: "{{ lookup('env', 'CLIENT_ID') }}"
    CLIENT_SECRET: "{{ lookup('env', 'CLIENT_SECRET') }}"

- name: Launch migrations and seeds
  hosts: added_hosts
  roles:
    - launch-migrations
  vars:
    GITHUB_USER: "{{ lookup('env', 'GITHUB_USER') }}"

- name: Refresh ELB health check
  hosts: localhost
  roles:
    - refresh-health-check
  vars:
    ELB_NAME: crm-api-lb
    AWS_REGION: "{{ lookup('env', 'AWS_REGION') }}"
