#  Deploy CRM api test
#
#  ansible-playbook ansible/deploy.yml
#

---
- name: Create IAM policies
  hosts: localhost
  roles:
    - create-iam-policies

- name: Create IAM role
  hosts: localhost
  roles:
    - create-iam-role
  vars:
    ROLE_NAME: crm_api
    ROLE_DESCRIPTION: Role to be used in crm_api instance
    MANAGED_POLICIES:
      - pdcw_ecr_allow_pull_images

- name: Setup internet_access security group
  hosts: localhost
  roles:
    - create_security_group
  vars:
    AWS_REGION: "{{ lookup('env', 'AWS_REGION') }}"
    VPC_ID: "{{ lookup('env', 'VPC_ID') }}"
    NAME: internet_access
    DESCRIPTION: Allow access from internet
    TAGS:
      Name: internet_access
    RULES:
      - proto: tcp
        ports:
          - 443
        rule_desc: Allow
        cidr_ip: 0.0.0.0/0

- name: Setup ssh security group
  hosts: localhost
  roles:
    - create_security_group
  vars:
    AWS_REGION: "{{ lookup('env', 'AWS_REGION') }}"
    VPC_ID: "{{ lookup('env', 'VPC_ID') }}"
    NAME: ssh_access
    DESCRIPTION: Allow access through ssh
    TAGS:
      Name: ssh_access
    RULES:
      - proto: tcp
        ports:
          - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: allow inbound connections via SSH (IPv4)

- name: Create ec2 instance
  hosts: localhost
  roles:
    - create-ec2-instance
  vars:
    AWS_ACCOUNT_ID: "{{ lookup('env', 'AWS_ACCOUNT_ID') }}"
    AWS_REGION: "{{ lookup('env', 'AWS_REGION') }}"
    SECURITY_GROUP_NAMES:
      - internet_access
      - ssh_access
    IAM_ROLE_NAME: crm_api
    INSTANCE_TYPE: t3.nano
    IMAGE: ami-0fc970315c2d38f01
    VPC_SUBNET_ID: "{{ lookup('env', 'VPC_SUBNET_ID') }}"
    VPC_ID: "{{ lookup('env', 'VPC_ID') }}"
    KEY_NAME: "{{ lookup('env', 'KEY_NAME') }}"
    NAME_TAG: "{{ lookup('env', 'NAME_TAG') }}"
    TERMINATION_PROTECTION: "{{ lookup('env', 'TERMINATION_PROTECTION') }}"

- name: Add instance to inventory group
  hosts: localhost
  roles:
    - add-instance-to-inventory-group
  vars:
    NAME_TAG: "{{ lookup('env', 'NAME_TAG') }}"
    AWS_REGION: "{{ lookup('env', 'AWS_REGION') }}"
    ANSIBLE_USER: ec2-user

- name: Create swap file
  hosts: added_hosts
  roles:
    - setup-swapfile
  vars:
    SWAP_SIZE: 1G

- name: Install dependencies
  hosts: added_hosts
  roles:
    - install-dependencies
